/* DO NOT EDIT THIS FILE - it is machine generated */


#ifdef ON_LINUX
    #include "jni_linux64.h"
#else
    #include "jni.h"
#endif

/* Header for class io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api */

#ifndef _Included_io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
#define _Included_io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    init
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_init(JNIEnv *, jobject);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    ffxFsr2GetScratchMemorySizeGL
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2GetScratchMemorySizeGL(JNIEnv *, jobject);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    ffxFsr2CreateContext
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2CreateContext(JNIEnv *, jobject);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    ffxFsr2GetInterfaceGL
   * Signature: (IFIII)I
   */
  JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2GetInterfaceGL(JNIEnv *, jobject, jint, jfloat, jint, jint, jint);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    ffxFsr2Test
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2Test(JNIEnv *, jobject);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    ffxFsr2ContextDestroy
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2ContextDestroy(JNIEnv *, jobject);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    getGPUInfoNV
   * Signature: ()Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_getGPUInfoNV(JNIEnv *, jobject);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    getGPUInfoAMD
   * Signature: ()Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_getGPUInfoAMD(JNIEnv *, jobject);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    ffxFsr2ContextDispatch
   * Signature: (IIIIIIFFFFIIZFFFZFFFFZII)I
   */
  JNIEXPORT jint JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxFsr2ContextDispatch(JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jboolean, jfloat, jfloat, jfloat, jboolean, jfloat, jfloat, jfloat, jfloat, jboolean, jint, jint);

  /*
   * Class:     io_homo_superresolution_fsr2_nativelib_ffx_fsr2_api
   * Method:    ffxGetTextureResourceGL
   * Signature: (JIII)Lio/homo/superresolution/fsr2/types/FfxResource;
   */
  JNIEXPORT jobject JNICALL Java_io_homo_superresolution_fsr2_nativelib_ffx_1fsr2_1api_ffxGetTextureResourceGL(JNIEnv *, jobject, jlong, jint, jint, jint);
#ifdef __cplusplus
}
#endif
#endif
